### ISSUE TITLE
EV3Sim Lists wrong behaviour

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/robertalab#1008]
**Describe the bug**
There are two wrong behaviours in the List functions for the EV3 simulation.
1. `in list x insert at # from end` the inserted element is misplaced (this is also the case for `in list x get and remove # from end`)
2. `in list x remove #` does not delete the element

**To Reproduce**
1. Create the following program:
![image](https://user-images.githubusercontent.com/7438960/46138257-b59b7500-c24b-11e8-8c3e-62fba06ebfbe.png)

2. Create the following program:
![image](https://user-images.githubusercontent.com/7438960/46138387-1165fe00-c24c-11e8-805b-bd9e48f06e06.png)

**Expected behavior**
1. The shown list is [0, 0, 0, 1]
2. The shown list is [0, 2]

**Comment by VinArt** [comment]
1. actually this is indeed the expected behaviour, because the insert operation puts an element at the desired index and if any element exists prior to this operation at this index it (and all the elements to the right) will have their index incremented by one
2. needs checking, probably the operation cannot be done in-place.

**Comment by VinArt** [comment]
Fixed 2.
![image](https://user-images.githubusercontent.com/3738015/48915720-04e2d800-ee80-11e8-9e78-6f96a7c2f04f.png)
