### ISSUE TITLE
Trailing space in the program documentation / description leads to an error, related to #910

### ISSUE THREAD

**Issue by bjost2s** [OpenRoberta/robertalab#1062]
**Describe the bug**
 - Programs with a trailing space (maybe with other special charakters) can be saved but not loaded anymore
**To Reproduce**
1. Log in
2. Click on documentation view on the right panel
3. Write text with a trailing space e. g. "test "
4. Click on "export program"
5. Click on "import program"
6. Open "abc"
![image](https://user-images.githubusercontent.com/1613069/48669822-687da600-eb0c-11e8-8f0b-13bfc2cc9e08.png)

**Expected behavior**
 - "abc" should be shown

**Error message on server side**
 2018-11-18 08:22:53,105 [qtp1335050193-33] session-id=[1] user-id=[4] robot-name=[ev3lejosv1] ERROR de.fhg.iais.roberta.util.Util - Possible XSS: program description does not match sanitised value. Info: no info available / user not logged in

**Additional context**
 - Programs like this simple one could be saved, but not loaded again
 - no error message is shown, loading is just ignored!

**Comment by VinArt** [comment]
So as stated, I replace `&nbsp;` with whitespace, so the sanitiser does not complain that they are two different strings.

However, I am not sure what the `6. open "abc"` means and why "abc" should be shown for the description after "test " was written there. 

Another thing is that despite sanitiser not complaining anymore, I could not achieve "test " to be shown, because the trailing spaces are stripped. Maybe they should be stripped on export as well? If the description text would be right stripped, then this issue would not occur.
