### ISSUE TITLE
USBProgram: Make custom IP server / port persistent

### ISSUE THREAD

**Issue by pablopoo** [OpenRoberta/robertalab#1109]
**Is your feature request related to a problem? Please describe.**
Users have to enter custom server every time the app is open

**Describe the solution you'd like**
Make this setting persistent.

**Comment by boonto** [comment]
Thanks for the request.

For persistent changes in the USBProgram we have to consider how we integrate it without changing the user experience or confuse users.
E.g. one pupil could activate the option and close the USBProgram, the next pupil starting the program could not connect to the default lab.open-roberta.org because it does not know about the setting.

So we'll have to think about a nice way to realize this.

**Comment by boonto** [comment]
The last 5 addresses are saved now, you just have to press on the advanced options dialog and the last used one should already be filled in.
Preview:
![image](https://user-images.githubusercontent.com/7438960/54198185-21a22a80-44c6-11e9-9f7e-8245f9edd50b.png)

**Comment by VinArt** [comment]
Is this merged to develop?

**Comment by boonto** [comment]
Yes, should be: https://github.com/OpenRoberta/robertalab-usbprogram/commit/f3c154e700984573b1478240872d5494eca25fcb
