### ISSUE TITLE
Start program button behaves non user-friendly for token based robots

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/robertalab#1124]
**Describe the bug**
the run program button, after pressed, becomes inactive for a short time and is enabled very soon, even before the message "program will start" appears. This will confuse users. Pressing the button a second time gives the error message "robot not active", which is confusing too.

**To Reproduce**
write a small program and press the run button (twice ...)

**Comment by rbudde** [comment]
we have the same problem with ALL arduinos.

**Comment by bjost2s** [comment]
The problem is at server side. Once the run button is pressed, the gui sets the run button correctly to disabled. The program starts to be processed on server side. Here we change the robots state to "busy", when the compiler workflow has succeeded. During the time a regular (<3s) ping is asking for the robots state and gets the correct info "wait" so that the gui switches back to enable the run button. 
We should introduce a new robot state on server side e.g. "compiling" which will return "busy" to the gui but accepts a new download like "wait".
On gui side we could only interrupt the ping until we got a response from the compiling (and download).

I would prefer the server solution, because with the new state we could block the robot for other run commands (only interesting if more clients are connected to one robot, used in schools for ev3 afaik)
