### ISSUE TITLE
Turn block + drive block

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#209]
The robot turns (left or right) then the robot turn back and drives forward. 

The robot behaves normal if there is a wait between trun block and drive forward block

**Comment by elhele** [comment]
The problem was in motor synchronisation parameter in drive block. It is fixed now in commit a1f9d83

**Comment by bjost2s** [comment]
The robot now doesn't drive straight forward because of missing synchronization. So adding synchronization flag back is recommended. The above mentioned problem can only be solved by adding a `Wait(1)` command after each `RotateMotorEx` command. This solution is not nice and if someone finds a better way, please post it here. Btw `ResetBlockTachoCount` is not working.
