### ISSUE TITLE
Stop program

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#218]
Program should be stopped via Open Roberta Lab

The start button could be change to stop button. 

This would help to stop programms with endless loops

**Comment by ensonic** [comment]
This won't work right now, as we suspend the the push protocol while the program runs. Other than that I would prefer this behaviour too, maybe plan properly and do it after 2.0

**Comment by bjost2s** [comment]
only for ev3, the only robot connected via wifi

**Comment by ensonic** [comment]
In the long run I'd like to keep to make a change to the protocol to keep it running while the program runs, but it is not a simple as it sounds:
* the program can also be run from the robot, people need to understand that in that case, the will have to stop it from the robot
* when running from the robot, the programm needs to understand that it is not conencted to the robertalab, so that it won't try to send telemetry data
* only robots with a link (wifi, bluetooth, cable?) could potentially support stopping the execution from the UI

**Comment by rbudde** [comment]
not feasable at the moment
