### ISSUE TITLE
No Connection ...

### ISSUE THREAD

**Issue by thski** [OpenRoberta/robertalab#23]
When I wanted to set up a connection and entered the token within openroberta, I always got an error, although I could connect via ssh.

After some hours of trying I found a workaround: I called ora.sh with the options -libs and -menu:

./ora.sh -libs
./ora.sh -menu
./ora.sh --start

and then when I started the connection on the EV3 I was asked for the IP of my server-PC, which I was not asked before. I entered it (xxx.xxx.xxx.xxx:1999) and got a token which I entered on the PC and voilà, it worked! But I didn't find this information in any faq or tutorial. So I would suggest to add this to the tutorial or to make the process easier for the user, please.

Everything works fine now. Time to say thank you!

**Comment by dpyka** [comment]
Thanks for your feedback. We agree with that. In the next release, you will be able to toggle the setting directly from within the menu on the brick (from the system sub menu), without copying anything. It turns out, that copying files to the brick is a bit too clunky for a local installation of Open Roberta. This file upload was intended to be used by developers who make changes to the menu.
Maybe we should think about making a separate script only for the brick and exclude these functions from the ora.sh script to not further confuse people. The new script would not be relevant for them.
