### ISSUE TITLE
OR Simulator - unexpected behavior 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#471]
![or_sim_test](https://cloud.githubusercontent.com/assets/19221359/24764876/14c5aa86-1af6-11e7-89a5-797f1528f74d.png)

Expection: Robot drives backward 20cm then start steering again. 
Result: Robot stops shortly then start steering

**Comment by bjost2s** [comment]
The problem of this program ist that you either ask the touch sensor after driving backwards 30cm or after steering in a curve for 20cm . At this point the robot may be just be without contact to the touch sensor because it is rejected from the obstacle. Please try this more reactive program instead:
![image](https://cloud.githubusercontent.com/assets/1613069/24777936/34fd2ea0-1b28-11e7-9f56-099f7c6f9bfb.png)

**Comment by cvejoski** [comment]
It is better to use the ultrasonic sensor instead of the touch sensor, then the behavior of the program will be more obvious.

**Comment by Thorlogy** [comment]
thx
