### ISSUE TITLE
Cannot work with NAO

### ISSUE THREAD

**Issue by nicolaipoehner** [OpenRoberta/robertalab#486]
Dear all, 

i just found out about the support of Open Roberta Lab with NAO and immediately got started. I was able to install and connect to NAO but when I run a programm NAO doesn't do anything even though I am connected to the robot (at least that's what the green light is supposed to indicate) Any help? Thanks in advance! 
Nicolai

**Comment by JanisM91** [comment]
Hi Nicolai,

i will try to help with your issue. Can you provide some more information first?
Which version of the NAO (Hardware + Software) are you using?
Can you send a screenshot of the program you tested?

Additionally please try this simple program on your robot:
![test_program](https://cloud.githubusercontent.com/assets/22591228/25333751/dbb28b48-28eb-11e7-97ef-28179f280150.PNG)

Regards
Janis

**Comment by nicolaipoehner** [comment]
Hi Janis,

I'm using a Nao version V5 with Naoqi 2.1.4.13 running on it. The programm I tested was a simple hello world programm looking like this: 

![unbenannt](https://cloud.githubusercontent.com/assets/27953058/25376214/aed50d9a-29a3-11e7-9910-9f575af124d6.PNG)

I also tried your idea alredy but it didn't help.

**Comment by JanisM91** [comment]
Hi Nicolai,

thanks for the information your provided.

It seems like the version of your NAO is fine. There can't be a problem with the generated code or the HAL for the NAO. Otherwise NAO should say Error, if the uploaded program can`t be executed.

Therefore i conclude that there is a problem with the file transfer. The green icon just states that the connection between your PC and the Open Roberta Lab is established. It seems like there is a problem with the connection to your NAO. 
Can you evaluate if the IP, username and password are correct. Just trie to log into the web interface of the robot with the information.

Regards
Janis

**Comment by nicolaipoehner** [comment]
Hi Janis,

sorry I haven't answered in a while but I've been busy with other things. Well I tried and retried a couple of times but NAO does still not respond to any commands from OpenRoberta. I've double checked the ip address, username and password and the login to NAO's webpage always worked. Any other suggestions what I could try?

Kind regards,,
Nicolai

**Comment by JanisM91** [comment]
Hi Nicolai,

meanwhile i checked the connection and communication with the Open Roberta Lab with our NAO and it works just fine. So it doesn`t seem like there is a general problem.
I still think that there is a problem with the communication between your PC and your NAO.

Do you connect the NAO via Ethernet or WiFi? Are there any routers with firewalls in between or is the communication in the network restricted?

I´m looking forward to solve this issue as i haven`t encountered a similar issue, yet.

Regards
Janis

**Comment by JanisM91** [comment]
Hi Nicolai,

we made some changes on the backend of the connection program for NAO.
These changes should have fixed your issue. (There was a problem with the transfer of the HAL)
Please download the new version of the software from our wiki and test it with your robot.

I´m looking forward to hear from you.

Regards
Janis

**Comment by nicolaipoehner** [comment]
Dear Janis,

it still doesn't work. I has to be a transfer error since I downloaded the Python file and manually uploaded it onto the robot with Filezilla and it worked. However I had to get rid off some errors in a hal.py file which has been on the robot before (missing intended blocks, syntax errors, etc.) This file looked like a collections of definitions to convert the NEPO code to Python code. 
Since we are speaking of connections all the time, I was wondering whether you know how to connect NAO to a WPA2 Enterprise network (if possible?)? I was trying to configure wpa_supplicant.conf file on the robot but don't get it to work. After a little research others seemed to have this problem too. On the old NAO web page you see that NAO detects those networks but I can't connect to them since I can't configure it (type in identity and password, etc.). 

I'm looking forwad to hearing from you.

Regards,
Nicolai

**Comment by nicolaipoehner** [comment]
Dear Janis, 
just to anwser your other question: My NAO is connected via Ethernet (plugged in a switch in my office). The network is the university network eduroam. The potential wifis I could use are listed here:
https://www.rz.uni-wuerzburg.de/dienste/kommunikation/wireless_lan/verfuegbare_wlan_netze/

Kind regards,
Nicolai

**Comment by JanisM91** [comment]
Dear Nicolai,

thank you for your response. Now the installer in the wiki is up to date and hopefully working for you.(?) In a next step we will not make the hal.py file a ressource but a file that is send from the server. Therefore we don't have to generate a new installer for every change in the hal.py file and the users can use the programm they once installed.
You are quite right with your assumptions. The hal.py file is a collection of definitions and functions that is needed to execute the code generated from the Lab.

Ethernet is fine.

Regarding to http://doc.aldebaran.com/2-1/news/known_issues.html WPA 2 Enterprise is not supported in the current version of NaoQi. But it is listed in the Known Issues so i hope that Softbank Robotics are working on this issue and release a fix. As most universities and companies use the WPA2 Enterprise standard i think it would be nice to have that for NAO.

Kind regards
Janis

**Comment by nicolaipoehner** [comment]
Dear Janis, 

unfortunately it is not working since when I'm trying to start my program I get the error message that something is wrong with the download of my program and that I should try again. Any ideas? Sorry for bothering you.

Kind regards,
NIcolai

**Comment by JanisM91** [comment]
Dear Nicolai,

there is no need to feel sorry. ;)

Are you using the newest version? If you click on Info -> about it should say version 1.0.0.-SNAPSHOT.
The latest release is here: https://github.com/OpenRoberta/robertalab-naoprogram/releases

You can also try to have a look at the log file. Maybe this helps us to get closer to the source of this issue.
It should be located here: ...\Users\*USERNAME*\AppData\Roaming\OpenRobertaNAO

Feel free to send the log to me, if you want me to have a look please send it to the mail adress in my profile.

Regards
Janis

**Comment by ProCycon** [comment]
Hello Janis.
I have to jump in your conversation, because I have the same problem with my NAO und the connection between Open Roberta Lab. 
I am using the latest version of Open Roberta NAO with the Open Roberta Lab online under lab.open-roberta.org.
![version](https://user-images.githubusercontent.com/32300484/30862020-dba76276-a2cc-11e7-81f2-ddffe0a3eeb9.png)

My NAO is connected to my machine with ethernet and it seems, like the connection is fine. The green symbol in the application is showing. I checked the login several times and they are correct, because I can access with them the NAO web access. 
![verbindung](https://user-images.githubusercontent.com/32300484/30862130-55a2728c-a2cd-11e7-8e70-ea86ff3c1cd8.png)


When I try to upload the following programm to my NAO, I get the following message, stating, that the transfer did not work and I have to try again. 

![program](https://user-images.githubusercontent.com/32300484/30862292-de5d87e2-a2cd-11e7-962f-ad1fbadc6bd8.png)


![error](https://user-images.githubusercontent.com/32300484/30862240-a509f9da-a2cd-11e7-8d48-7728e3e7d1c2.png)

Do you have any suggestions, where I can look to solve my problem? If you need more informations, I will provide them.

With best regards,
Daniel

**Comment by bjost2s** [comment]
There was a problem in the NAO connection program. It is fixed now. Please checkout the newest installer here https://github.com/OpenRoberta/robertalab-naoprogram/releases and give it a try.

fixed with https://github.com/OpenRoberta/robertalab-naoprogram/commit/de0fcbb75b7ce0656b5f72b2532311adecba8ee1

**Comment by ProCycon** [comment]
Thanks bjost2s.
The new version works!
