### ISSUE TITLE
Arduino create agent integration

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/robertalab#492]
As a user I'd like to upload programs without using USB program and manual input of the token.

For this an Arduino create agent can be used. It is easier to install, launch and it doesn't require a token. 

User would have to download and install the Arduino Web Editor plugin (http://create.arduino.cc/getting-started/plugin). The plugin would be running in a tray (example for linux):
![pluginsign](https://cloud.githubusercontent.com/assets/13983474/25856417/3342f23a-34d6-11e7-829f-7665db64c06b.png)

If there is only one robot of a chosen type connected to the laptop it'll connected automatically and the robot's icon will change the color from grey  to blue:
![active](https://cloud.githubusercontent.com/assets/13983474/25993680/1a15eb78-370b-11e7-9aa8-bac861fe0fcf.png)
Otherwise user should go to Open-Roberta lab, choose a robot icon and press "connect":
![connect](https://cloud.githubusercontent.com/assets/13983474/25856479/678c7de0-34d6-11e7-9156-054228e00003.png)

After this user'll see the following pop-up:
![ardlist](https://cloud.githubusercontent.com/assets/13983474/25856521/87fe1124-34d6-11e7-97d3-2ee716946b75.png)
where would be listed all Arduino devices with ports attached to the user's computer. After choosing the device user can run a program on the robot. 

Proposed solution:

- [x]  Provide Arduino create agent preconfigured with Open-Roberta public key
- [x]  Provide install script for *nix-based OSs
- [x]  Implement web-sockets for listing available Arduinos with ports
- [x]  Implement GUI integration

**Comment by VinArt** [comment]
There is a problem with SSL certificates: they must be present on the system (so we need to use wss instead of ws connection) AND the user must accept this local self-signed certificate.

**Comment by VinArt** [comment]
Testes today a fresh install of create agent on both windows and linux. For some reason it is not shipped with avrdude and thus fails to flash boards. The problem is in /home/<username>/.arduino-create folder. The file "installed.json" should be modified to look the following way:

`{"apilevel":"v1","avrdude":"/home/<username>/.arduino-create/arduino/avrdude/6.3.0-arduino9","avrdude-6.3.0-arduino9":"/home/<username>/.arduino-create/arduino/avrdude/6.3.0-arduino9"}`

On Linux platform. On Windows it should be edited in the similar way, namely:

`{"apilevel":"v1","avrdude":"C:/Users/<username>/.arduino-create/arduino/avrdude/6.3.0-arduino9","avrdude-6.3.0-arduino9":"C:/Users/<username>/.arduino-create/arduino/avrdude/6.3.0-arduino9","windows-drivers":"C:/Users/<username>/.arduino-create/arduino/windows-drivers/1.8.0","windows-drivers-1.8.0":"C:/Users/<username>/.arduino-create/arduino/windows-drivers/1.8.0"}`

This implies that the user is able to copy the appropriate version of avrdude and for Windows the drivers to the aforementioned locations.
For reasons unknown, the current installer does not do this automatically. If we will be providing our own version (and we will, hence the configuration is different) then we can as well copy the needed resources and configuration.

**Comment by VinArt** [comment]
UPD: it is possible to send a command over websocket to create-agent to download the needed tool, like avrdude, and that will automatically change the json file. But this requires Internet connection.
