### ISSUE TITLE
Feature request: random numbers for Beginners

### ISSUE THREAD

**Issue by alexgit2k** [OpenRoberta/robertalab#586]
Random numbers are part of beginner programms like dice, rock–paper–scissors, oracle, ... but in NEPO it is only available for Experts. Therefore the random integer block should be available for Beginners.

![beginners](https://user-images.githubusercontent.com/7514221/29096731-8b77b7c6-7c96-11e7-9128-a37d9e07b0b2.png)

**Comment by bjost2s** [comment]
We discussed this and I think we will give it a try. The problem was, that we 
- want  to keep the beginner toolbox small
- beginners, exspecially 3. class kids have no idea, what a random number really is.
- usually we keep the lab consistent, that means we would have to change all beginner toolboxes from the different systems, that we support. But for our robots, like EV3 or NXT, nobody has asked for this because it is not used in beginner mode.
I personally would suggest to use sensor values to make decisions and not random values.

**Comment by alexgit2k** [comment]
Thanks. Using sensor values for random numbers are no option, they are not random and the range has to be transformed to the required range which requires much more knowledge than 3rd grade.
Unterstanding random numbers was no problem, randomness is even part of 1st class.
