### ISSUE TITLE
Unable to move sensor block out of "wait until" block

### ISSUE THREAD

**Issue by alexgit2k** [OpenRoberta/robertalab#587]
In the control-block "wait until" the sensor-block ("get button (pressed) A") can not be moved out only the complete logic-block and the small logic-block ("true"):

![wait](https://user-images.githubusercontent.com/7514221/29096826-fada18d4-7c96-11e7-954f-c22909659ccc.png)

**Comment by bjost2s** [comment]
This is wanted, because these three blocks are internally connected. Usually blocks are undependent, but here, we have to change the surrounding logic block, if the inner sensor block changes, eg the type.

**Comment by alexgit2k** [comment]
Can you visualize this behaviour by e.g. using the control-block-color for the logic-block and removing the borders? It is currently not understandable why the block can not be moved and I have seen several unsuccessful tries.

**Comment by ensonic** [comment]
Just to mention. I was not aware of this and always thought it is a blockly bug :/ I think it is unexpected because you can manually assemble the logic block and then also disassemble it again. When using a logic block that you manually assemble, of course you need to remove both blocks before you can change the type.

**Comment by bjost2s** [comment]
Think we can make it movable and offer this block also in the toolbox. We will see how it works ;-)

**Comment by bjost2s** [comment]
fixed with #697
