### ISSUE TITLE
EV3 pop-up massage after connect/disconnect 

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#628]
After re-connecting the EV3 via USB a pop-up appears: 
Das Open Roberta Lab ist zur Zeit nicht erreichbar. Bitte überprüfe deine Internet Verbindung und lade diese Webseite neu. Falls das Problem weiterhin besteht, schreibe bitte eine Mail an folgende Adresse: roberta-zentrale@iais.fraunhofer.de 

This message is missleading (wrong), e.g. website reload is not necessary.

**Comment by bjost2s** [comment]
This only appears on windows and while using the usb program with ev3!
Problem is, that windows switches the network for a short time. There is currently no way to filter it out, because it is correct: The client computer thinks for a short time, that it is not connected to the internet anymore. The message is correct, but windows cannot distinguish.

**Comment by Thorlogy** [comment]
I would like to recommend to change the massage as following:

Die Internet-Verbindung wurde unterbrochen. Solltest du gerade deinen Roboter per USB Verbunden haben, genügt ein Klick auf die Programmieroberfläche. 

Falls das Problem weiterhin besteht, überprüfe deine Internet-Verbindung und lade diese Webseite neu. Sollte das Problem erneut auftreten, schreibe bitte eine E-Mail an: roberta-zentrale@iais.fraunhofer.de
