### ISSUE TITLE
assigning a new array cause a compiler error, calliope2017

### ISSUE THREAD

**Issue by kwollw** [OpenRoberta/robertalab#735]
![nepo-calliope-bug-listen1](https://user-images.githubusercontent.com/6341023/34652752-ab5266a4-f3e2-11e7-9758-377b0e234e16.png)

Declaration and instantiation (lines 11,15) restrict list (`<array>`)  to 3 elements.

Assigning a new list with more elements is possible in nepo block language but will cause an  error in cpp (line 17).

**Comment by elhele** [comment]
Now we use a library that allows assigning a new array only of the same length. We will add a possibility to assign an array of a different length in the release after the upcoming one.

**Comment by bjost2s** [comment]
we should immediately switch back to array, otherwise current programs will not be compilable anymore:
@VinArt and @elhele, please make sure not to work on tickets that do not belong to a dedicated project. Here we have a good example where no review has happened, because it is not in any project. Unfortunately the solution is bad, because it will probably break other working code, because you cannot use a list in the same way like an array.

![image](https://user-images.githubusercontent.com/1613069/37603247-78280318-2b8e-11e8-8e86-7fc4da2d289e.png)

@VinArt, please undo this. We will discuss this issue further in

**Comment by bjost2s** [comment]
The problem of assigning arrays in c is much more complex than expected and will be solved in general here #797 or in sub issues from #797
