### ISSUE TITLE
configuration tab name bug

### ISSUE THREAD

**Issue by elhele** [OpenRoberta/robertalab#772]
When I move a configuration block, robot name disappears from configuration tab name:

![image](https://user-images.githubusercontent.com/13983474/36482460-abeed7ec-1713-11e8-8964-aba64945dc54.png)

The example is for EV3, but it is the same for all robots with configuration.

**Comment by bjost2s** [comment]
At the moment you change something in the configuration, this configuration is not a basic configuration anymore. It becomes automatically a configuration from the specific NepoProg. Once you save the program, your configuration gets the name of your program, if you export your program this specific configuration is exported too. The only way to destingiush between the bascic configuration and the modified one is the name. 
This is not a bug. We cannot give this configuration a name at that moment, because we don't know which one. Feel free to play around with the configuration saved by the program or saved seperatly by the configuration tab itself.
