### ISSUE TITLE
Text 2 Speech Ipad Simulation

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#777]
The Text2Speed Block is not working in the Simulatoin on Ipad 
Tested with Chrome and Safari - latest OS version

**Comment by boonto** [comment]
According to [Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis#Browser_compatibility) and [Browser support](https://developers.google.com/web/updates/2014/01/Web-apps-that-talk-Introduction-to-the-Speech-Synthesis-API?hl=en#browser_support) iOS/Mobile Safari 7.1 is partially supported. [Here](https://developer.apple.com/documentation/webkitjs/speechsynthesis) it says Safari Mobile 9.0+, so I guess it should work on the newest version.

Maybe its related to the soft mute functionality similar to [this issue](https://forums.developer.apple.com/message/293874#293874).

I can not test it right now, because I do not have an IPad.

**Comment by bjost2s** [comment]
not sure if Ipads allow this in general, so maybe it can't be fixed

**Comment by bjost2s** [comment]
@Thorlogy could you please check the settings provided in the similar issue @boonto has provided?

**Comment by boonto** [comment]
I found [this](https://stackoverflow.com/questions/32193704/js-speech-synthesis-issue-on-ios), apparently the user has to trigger the action, pure javascript will not work.

**Comment by rbudde** [comment]
To be reviewed later. Can't be fixed with the actual IOS versions due to security issues.
