### ISSUE TITLE
Bluetooth communication is not working

### ISSUE THREAD

**Issue by spidgorny** [OpenRoberta/robertalab#821]
Tried to test Bluetooth communication between two EV3 robots. I could not make it work. Is this supposed to work reliably?
Master:
![image](https://user-images.githubusercontent.com/1579235/37937007-210a89d2-3158-11e8-8ac6-b8dd95e7a6da.png)
Slave:
![image](https://user-images.githubusercontent.com/1579235/37937031-38ac63b2-3158-11e8-8bcb-312710ac5810.png)
Master beeps and after a ~ minute shows an error message:
![image](https://user-images.githubusercontent.com/1579235/37937067-5d294a70-3158-11e8-80cc-bdbe0d0389c5.png)
Slave waits for ~5 minutes and errors like this:
![image](https://user-images.githubusercontent.com/1579235/37937090-729b55ce-3158-11e8-89a4-1fd0436176dc.png)
Where are these error codes documented?
Any ideas what am I doing wrong?
Thanks.

**Comment by spidgorny** [comment]
Version: EV3 leJOS 0.9.1 on both devices.
Name "ev1" is set in (B)luetooth settings in menu.

Tried to pair devices to each other in advance - it says UNSUCCESSFUL.
What else can I try?

**Comment by bjost2s** [comment]
Make sure after renaming the ev3 that you have restarted the systems. 
Is bluetooth enabled on both robots?

**Comment by spidgorny** [comment]
BT was enabled - I hope this setting persists after restart because I didn't check every time.
I've reboted EV3 several times - it does not help. 
So you say it is working for you? Should pairing of two EV3 to each other be done in advance or this is irrelevant? What does these two error codes mean?

**Comment by bjost2s** [comment]
It should work. Could you please test it with "EV3" as the name of the brick?. I'm not sure what setting the name in the Bluetooth settings means. So we tested it with renaming the robot via the system, so that the new name appears in the first line of the menu.
Could you also try this program for the Slave?
![image](https://user-images.githubusercontent.com/1613069/38051026-4ad5ff46-32cd-11e8-9fc8-95e476bf6fde.png)

**Comment by spidgorny** [comment]
Thank you. I've tried rebooting. I've tried your program as slave. Bluetooth is ON and visibility is ON. Tried connecting to "EV3". The error on master is now different "Could not connect in given time". Slave is just waiting with empty screen. This is confusing. Anything else I can try?
Do you have any way to enable debug mode or additional logging? Should I try the latest "master" branch commit? Are there any fixes to BT since leJOS 0.9.1?
Thanks.

**Comment by bjost2s** [comment]
Please revise your master program as well. The problem is, that you are trying to connect to the other EV3 in the loop, but EV3 can only hold and use one connection. 
I have attached two programs, master and slave, that work for us.
slave:
![image](https://user-images.githubusercontent.com/1613069/38289602-562a6fda-37d7-11e8-89e8-c0b88c5ff854.png)
master:
![image](https://user-images.githubusercontent.com/1613069/38289622-6e0a2744-37d7-11e8-97b4-820365eea430.png)
We will try to make it more clear in the help section for the blocks.

**Comment by spidgorny** [comment]
It works with a single connection. (Or maybe after firmware update). Thank you for your help.
"Slave" has to be the actual name of the brick. It's "ev1" in my case.

**Comment by bjost2s** [comment]
Thanks for your feedback
