### ISSUE TITLE
Blocks get stuck on top of other blocks when saving & and loading programs lossing data

### ISSUE THREAD

**Issue by lotu** [OpenRoberta/robertalab#832]
After saving a large program (I don't know the size just that I haven't replicated with a small program), blocks in the save file appear on top of each other and it appears that some blocks are lost, at the very least the code structure is lost.  This is bad because the user's program is not saved when it should be resulting in data loss.

Example of how this manifests in the UI after trying to load one of the programs.

![eqtnigts0oe](https://user-images.githubusercontent.com/120244/38388931-c39e0a2c-38ea-11e8-9862-eff0553a1533.png)

I made three programs "displaythings" displaythings2" and "displaythings3" I was trying to progress with a program between these files but you can see fewer blocks exist in the later programs.  You can see the programs in the "Gallery", shared by Lotu.  I don't know how to provide links to them.

**Comment by bjost2s** [comment]
Hi Lotu,
it is quite hard for us to reproduce this error, but I think the problem is a procedure block with returning a string array. 
We are very close to setting online the new version of the lab, 2.6.0/2.6.1 and it is very likely, that we have already fixed this bug. So please let's check this again, when the new version is online.
Thank you!

**Comment by lotu** [comment]
Okay sounds good how will I know when the new version is online?
