### ISSUE TITLE
calliope simulator compiles the program twice

### ISSUE THREAD

**Issue by rbudde** [OpenRoberta/robertalab#882]
situation: calliope program ready for simulation
action: press simulation button, effect: program is compiled (and probably not used)
action: press run simulation button, effect: program is compiled again and then executed

**Comment by bjost2s** [comment]
This is the same situation for all other simulations,microbit, ev3 and nxt. The reason is that we want to know if the blocks become maybe annotated or even if the program is compilable before we open the simulation. Once the simulation is open we ask for a new compilation each time you press start, because the user may have changed the blocks (we only track so far if programs are saved, not just changed).
We could think about checking if the xml has been changed, before asking for a new compilation.
