### ISSUE TITLE
NXT Simulation: "set colour sensor" fails

### ISSUE THREAD

**Issue by boonto** [OpenRoberta/robertalab#902]
When a "set colour sensor" block from the expert Action/Lights category is in task the simulation won't open/the program won't run.

**Comment by bjost2s** [comment]
This actor can't be support in the simulation so you should get a hint on client side.

**Comment by bjost2s** [comment]
However, this block is implemented in the simulation and I made it executable again. But we should think about it, because here we do not care about the configuration. Usually we only support the standard configuration for the simulation, but here we ignore the light sensor at port 3 and support the colour sensor action at port 3!
