### ISSUE TITLE
Missing loop block in toolbox category 1 for calliope and nao

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#916]
![image](https://user-images.githubusercontent.com/19221359/41393172-cfd1d3dc-6fa4-11e8-814e-62c506501e53.png)

This block is missing for calliope mini and nao within the toolbox category 1 
For all other available systems this block is available within the toolbox category 1

**Comment by bjost2s** [comment]
for the last release we agreed on removing this block from the beginner toolbox and replace it by this block:
![image](https://user-images.githubusercontent.com/1613069/41638054-760f67da-7457-11e8-8b4b-6a1b26e57bef.png)
The reason is that for robotics /embedded systems the counter loop block is practically not needed. It is much more important to teach beginners to deal with conditions like the new block.
If we you want to revert it, the new loop with condition has to be removed from the beginner toolbox, because the beginner toolbox should really stay small.
