### ISSUE TITLE
Move cookie acceptance dialog to top of screen to avoid it hiding the start button

### ISSUE THREAD

**Issue by mmarschall** [OpenRoberta/robertalab#929]
The current cookie acceptance banner covers the lower part of the screen. 

It covers the "run" button, which is confusing to children who want to get started with their program.

We should move the cookie acceptance banner to the top of the screen so that it doesn't hide any important UI elements.

**Comment by ilincasuzana** [comment]
There's menu items at the top and the logo at the right. What about bottom left?

**Comment by bjost2s** [comment]
This is afaik intended, because you force the user to read it and to decide.

**Comment by ilincasuzana** [comment]
I just committed moving it to the left. Should I revert?

Personally I'm also in favor of making it less invasive but I'm not sure what the official requirements are.

**Comment by bjost2s** [comment]
@Thorlogy, could you please comment on this?

**Comment by Thorlogy** [comment]
I would suggest placing the cookie hint so that it is clearly visible but does not obscure the run button. I will discuss it internally tomorrow and make an officially agreed proposal.

**Comment by mmarschall** [comment]
any guidance on how to place the cookie hint?

**Comment by Thorlogy** [comment]
@mmarschall We have decided to leave the cookie notice as it is.

Due to the fact that we work with publishers such as Cornelsen, who rely on the layout to look the same over a longer period of time, all layout adjustments / changes should only be made if they are based on a bug or an absolutely necessary usability decision. 

If the layout differs from the printed version too often or at critical points, the pupils may no longer be able to find their way around. We definitely want to avoid that.

**Comment by ensonic** [comment]
Thanks for sharing your thoughts. FYI: this change was made as a result of observing how often kids are puzzled with this notice covering some essential UI elements. Since we use anonymous guest sessions (like incognito mode), this notice comes up every time.

**Comment by Thorlogy** [comment]
Thank you. This is an important hint for us. We'll discuss this within our next meeting again.

**Comment by bjost2s** [comment]
if we put it on top of the screen, it will hide the menu. The result of a hidden menu is different, but also there kids will not see, that they can use the menu and all the functionality.

**Comment by mmarschall** [comment]
What about just making it slimmer?

Beate Jost <notifications@github.com> schrieb am Mi. 4. Juli 2018 um 23:06:

**Comment by Thorlogy** [comment]
Yes, I think it will come to such a solution. 
We'll probably just make the hint a little shorter. Thus the start button would remain visible despite.

**Comment by philippmaurer** [comment]
As discussed with parts of the team, we decided to make the cookie disclaimer just a little bit slimmer on large screens, (640px+ or tablet+) so that the cookie disclaimer will no longer hide important UI elements.
On small devices the cookie disclaimer will be moved slightly up, so it is floating on the screen. 

Screenshots:
Large screens: 
![grafik](https://user-images.githubusercontent.com/10925094/42522642-eb391f8c-846b-11e8-8bbd-06768e16ac21.png)

Small screens: 
![grafik](https://user-images.githubusercontent.com/10925094/42522721-29a922c6-846c-11e8-98d8-43a11a4cc18b.png)



This behavior will allow all users to see the relevant UI elements all the time, but will still force them to either accept or refuse the cookie disclaimer to work with the lab on a long run.

**Comment by bjost2s** [comment]
For small screens it looks a bit different, because the normal case is that the start popup is visible like here:
![image](https://user-images.githubusercontent.com/1613069/42523761-ff3d5ad6-846e-11e8-82b1-2d19fd890143.png)
For me it looks a bit unsorted now.

**Comment by bjost2s** [comment]
here an example for Iphone 5
![image](https://user-images.githubusercontent.com/1613069/42523846-37dd6df4-846f-11e8-9cf0-913391c0939d.png)

**Comment by philippmaurer** [comment]
We decided to move the cookie disclaimer back to the bottom of the screen for small devices, because of the design issues mentioned above.

This will affect devices like smartphones and small phablets.

**Comment by bjost2s** [comment]
I will close this issue, because I think it is already resolved and because of #1155
