### ISSUE TITLE
Calliope: Block "Show text '-2147483648'" produces hardly recognizable compiler error

### ISSUE THREAD

**Issue by kunkunuzzi** [OpenRoberta/robertalab#974]
There seems to be a toolchain bug for Calliope, which lets the conversion of -2^31=-2147483648 into a string end up in a compiler error. 
-Only this number seems to be affected (but also any number not fitting in a signed int) 
- This bug affects other blocks with implicit number to string conversion too
- only compile time conversion (of constants) is affected, not the runtime. 
- It seems not to occur in the simulator.

It seems, that an itoa-call in the constructor of ManagedString will cause the problem, with a nice discussion to this here:
https://stackoverflow.com/questions/39929982/itoa-c-implementation-int-min-underflow

Maybe this could be catched in the gui or corrected in the tool chain or the constant before compiling simply replaced by a string or catched by a meaningful message.

**Comment by VinArt** [comment]
Hi @kunkunuzzi, thanks for posting this issue. Unfortunately, we cannot really deal with it, since it comes from a third-party library, namely https://github.com/lancaster-university/microbit-dal/blob/master/source/types/ManagedString.cpp. You could, however, file an issue with the lancaster-university/microbit-dal and when they fix it, we will be happy to update our resources.

We are considering better user notification of the compiler errors, so that might be helpful further in situations like this. Thanks again.
